### ISSUE TITLE
Issue with GTX1060 in Direct Mode

### ISSUE THREAD

**Issue by ideaRunner** [OSVR/OSVR-Docs#103]
Hi, every one
    I got a problem with the Direct Mode of OSVR. GTX1060 Driver ver 376.09 
    I can use _D3D Present Example 3D_ to test my Direct Mode. There is a colorful box in my OSVR HDK2. However, when I want to run some demo, such as _VRShowdown_Pkg_, HellicottCity_OSVR that downloaded from _itch_, the demo first let me to select the creen and the screen resolution. There is only one screen that I used and selected (no extend screen of HDK2). Then I click play. Finally the demo is playing in my own screen rather than HDK2.
    I have read lots of reference. I notice that if there is some problems with my GPU driver. My Driver ver 376.09. I know that some driver versions such as 365 is good for it. But the pre-driver  does not support GTX1060. So is there any way to use GTX1060 with Direct Mode? 
    Any reply will be appreciated. Thank you.

**Comment by DuFF14** [comment]
If you see the colored room in the RenderManager examples, direct mode is working. I created Hellicott City a couple years ago before OSVR Direct Mode existed, and haven't gone back to update it. That's probably an old version of Showdown, too.

Other working demos can be found at https://github.com/OSVR/OSVR-Unity-Palace-Demo/releases
or
https://github.com/OSVR/Unity-VR-Samples/releases
