### ISSUE TITLE
Document the Google Custom Search Engine we have for OSVR

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Docs#5]
The public URL is https://cse.google.com/cse/publicurl?cx=016285390483464504735:ifzwvrb3lp4 for use outside of "being embedded in the top navbar of osvr.github.io"

**Comment by alfa256** [comment]
How should it be documented? Under **Getting Support** as a resource ?

**Comment by rpavlik** [comment]
That seems reasonable - it searches all of osvr.github.io, the github repos, plus the mailing lists, the dev blog, and at least in theory the gitter chat archives.
