### ISSUE TITLE
How To Delete Saved Video Tracker Calibration Utility Info? 

### ISSUE THREAD

**Issue by Balderick** [OSVR/OSVR-Docs#63]
With reference too https://github.com/OSVR/OSVR-Docs/blob/master/Getting-Started/HDK/Video-Based-Tracking-Calibration.md

I just upgraded to osvr 1204 runtime by uninstalling 1197 with revo uninstaller, rebooting, running a registry cleaner and then rebooting before installing 1204 and rebooting once more before trying to launch osvr server but video tracking camera does not start up with osvr server.

Using windows camera app the camera switches on and confirms camera and leds on faceplate of hdk are working.

when osvr server is started with osvr_server_config.HDK13ExtendedLandscape.sample.json saved as osvr_server_config.json i see: 
`[OSVR Server] Using default config file - pass a filename on the command line to use a different one.`
`[OSVR Server] Using config file 'osvr_server_config.json'`
`[OSVR Server] Constructing server as configured...`
`[OSVR Server] Loading auto-loadable plugins...`
`[OSVR Server] Loading plugins...`
`[OSVR Server]`
`[OSVR Server] Instantiating configured drivers...`
`[OSVR] Added device: org_osvr_filter_videoimufusion/HeadFusion`
`[OSVR] Client context initialized for org.osvr.analysisplugin`
`[OSVR] Interface initialized for /com_osvr_Multiserver/OSVRHackerDevKitPrediction0/semantic/hmd`
`[OSVR] Interface initialized for /com_osvr_VideoBasedHMDTracker/TrackedCamera0_0/semantic/hmd/front`
`[OSVR Server] Successes:`
`[OSVR Server]  - com_osvr_VideoBasedHMDTracker/VideoBasedHMDTracker`
`[OSVR Server]  - org_osvr_filter_videoimufusion/VideoIMUFusion`
`[OSVR Server]`
`[OSVR Server]`
`[OSVR Server] Aliases found and parsed from config file.`
`[OSVR Server] Display descriptor found and parsed from config file.`
`[OSVR Server] RenderManager config found and parsed from the config file.`
`[OSVR Server] Triggering automatic hardware detection...`
`[OSVR Server] Registering shutdown handler...`
`[OSVR Server] Starting server mainloop: OSVR Server is ready to go!`
`[OSVR] Performing hardware auto-detection.`
`[OSVR] Added device: com_osvr_Multiserver/OSVRHackerDevKit0`
`[OSVR] Added device: com_osvr_Multiserver/OSVRHackerDevKitPrediction0`

Control panel devices and printers, windows devices app and device manager all say camera is well and alive with no health issues.

I can not get camera to start using the osvr video tracking calibration utility to save a new set of beacon settings.  All i see is a command prompt window with:
`[OSVR Video Tracker Calibration] Using default config file - pass a filename on the command line to use a different one.`
`[OSVR Video Tracker Calibration] Using config file 'osvr_server_config.json'`

When Tracker Viewer is run all i can see is 
`[OSVR] Connecting to default (local) host`
`[OSVR] Client context initialized for org.osvr.trackerview`
`[OSVR] Could not connect to OSVR server in the timeout period allotted of 200ms`

`[TrackerViewer] No arguments passed: default is as if you passed the following:`
`--pose /me/hands/left --pose /me/hands/right --pose /me/head`
`You can specify --pose or --orientation then a path, as many times as you want.`
`Pass the argument --help for more info.`

`[OSVR] Interface initialized for /me/hands/left`
`[OSVR] Could not resolve source for /me/hands/left`
`[OSVR] Interface initialized for /me/hands/right`
`[OSVR] Could not resolve source for /me/hands/right`
`[OSVR] Interface initialized for /me/head`
`[OSVR] Could not resolve source for /me/head`

**Comment by Balderick** [comment]
Have been describing other related issues and what i have tried to work around them at https://github.com/OSVR/SteamVR-OSVR/issues/75

The more recent posts there confirm that graphical window as well a command prompt open with trackerviewer now that i have connected a 1080p monitor to same gpu as hmd and that tracking camera never gets switched on when starting osvr server.   No positional tracking is working.

Using windows camera app proves that both the tracking camera and led array on hdk hmd are alive and well.
![wrkinirarrayncamera](https://cloud.githubusercontent.com/assets/6255884/16823088/4080204e-4959-11e6-88c5-2e1018a986b7.PNG)

Uninstalling and reinstalling osvr runtime does not reset saved beacon calibration config.

**Comment by rpavlik** [comment]
Are you using a Windows inside preview build? They have some issues with the tracking camera. Inability to load or a bad calibration file would not produce what you are describing, but you can just look in whatever config file you are using to find out the filename for the calibration file. It's not hidden in any search path: only sought in the current directory.

**Comment by Balderick** [comment]
Thanks for the feedback and info. No insider preview build installed.   Though looking at windows error logs is confirming there are errors related to windows insider program.   Will try to expand on that.

can confirm i am running 10586.494 consumer build of version 1511.

~~ can also confirm there is no file using `configfile key` syntax or name videotracker....    ...  
[snip][/snip]

``` json
{
    "description": "This configuration supports video (so-called 'positional') and IMU fusion tracking, in addition to orientation-only tracking, with the OSVR HDK. It is configured for RenderManager applications in non-direct extended-display landscape mode on HDK 1.3 optics.",
    "display": "displays/OSVR_HDK_1_3.json",
    "renderManagerConfig": "sample-configs/renderManager.extended.landscape.json",
    "drivers": [{
        "plugin": "com_osvr_VideoBasedHMDTracker",
        "driver": "VideoBasedHMDTracker",
        "params": {
            "showDebug": false,
            "includeRearPanel": true,
            "headCircumference": 55.75,
            "calibrationFile": "videotrackerCombinedCalibrationFile13.json"
        }
    }, {
        "plugin": "org_osvr_filter_videoimufusion",
        "driver": "VideoIMUFusion",
        "params": {
            "name": "HeadFusion",
            "input": {
                "imu": "/com_osvr_Multiserver/OSVRHackerDevKitPrediction0/semantic/hmd",
                "faceplate": "/com_osvr_VideoBasedHMDTracker/TrackedCamera0_0/semantic/hmd/front"
            },
            "eyeHeight": 0,
            "cameraIsForward": true
        }
    }],
    "aliases": {
        "/headSpace": {
            "translate": [0.0, 0.0, 0.04141],
            "child": "/org_osvr_filter_videoimufusion/HeadFusion/semantic/fused"
        },
        "/me/head": "/headSpace"
    }
}
```

as osvr_server_config.json but can not find that combinedcalibrationfile anywhere on any connected storage space.

~~ehmz should i be running pre alpha software?~~ dunno what all that was but was looking at C:\Program Files\OSVR\Runtime\bin\displays\OSVR

**Comment by Balderick** [comment]
The osvr driver issue of not showing as a problem device in device managrr and yet in imaging device properties event information describes the imaging device as not fully installed is causing osvr server to hang searching for a directx camera that it knows is connected somewhere.
The last few comments of my open issue in the steamvr-osvr repo describe the issue by using screenshots.

**Comment by Balderick** [comment]
HDK firmware 1.96 has camera and server behaving better..
