### ISSUE TITLE
Does webvr support rendermanager

### ISSUE THREAD

**Issue by redglass1984** [OSVR/OSVR-Docs#85]
I checked code https://github.com/OSVR/OSVR-Docs/blob/master/Integrating-Game-Engines/WebVR/webvr.md.

Seems only included Clientkit in Firefox. so I think it doesn't support Rendermanager.

So, how does WebVR supports direct mode?

**Comment by gfrolov** [comment]
Hi,

The current version of WebVR supports OSVR in extended mode (see note at the bottom of that document), however we started working on adding DirectMode functionality now. We're hoping to get it done within the next month!
We already have a bug opened on bugzilla where you can track the progress of implementation (you should see new activity on it soon)  - https://bugzilla.mozilla.org/show_bug.cgi?id=1276711

-Georgiy
