### ISSUE TITLE
Need help to make ART Tracking working

### ISSUE THREAD

**Issue by RalfRab** [OSVR/OSVR-Docs#88]
Hello,

I am trying to use ART tracking in OSVR.
Since it is listed as a supported device I am assuming, that I do not need to run an external VRPN Server.
I did the following:
1) setup a dtracking tracking sending a flystick to UDP port 5010 (currently I am using DTrack Recorder to playback)
2) I created the config file attached. 
[osvr_server_config.json.txt](https://github.com/OSVR/OSVR-Docs/files/523964/osvr_server_config.json.txt)
3) started the server
4) i started the OSVRTrackerViewer.exe /me/hands/right on the console
I always get the following output, from the output.txt file. Somehow it seems that OSVR is not receiving any data. I guess I make something wrong in a very simple way.
[output.txt](https://github.com/OSVR/OSVR-Docs/files/523974/output.txt)

If I am using a vrpn server and try the output of the VRPN server in a console (without OSVR) I can see that the vrpn server is getting data. So I do not expect the firewall to be a problem.

Maybe you can give me a useful hint.

Thanks

Ralf

**Comment by rpavlik** [comment]
It is currently supported through VRPN, so you do actually need to run a VRPN server. Typically I run the VRPN server on port 3884 (command line option to `vrpn_server`), and so to use that setup you'd change the `"server"` line to `"localhost:3884"` in the OSVR external device config. "externalDevices" in the OSVR server config file always refers to external VRPN devices, at least at this time. Let me know if you still need help. (I've used such a configuration with a SMARTTRACK with two standard tracked bodies plus a Flystick 3. If you have a Flystick 3, I actually have an improved device descriptor and config that I haven't gotten around to committing yet.)

**Comment by RalfRab** [comment]
Hello Ryan,

thanks for getting back to me.

I tried the following:

1)      Started DTrack and it is sending data to port 5010

2)      I started a vrpn server with the attached config, listening to 5010.  (VRPN has version 7.30)

3)      I started vrpn_print_devices to see if I get data. And I can see that data is coming in.

4)      I start OSVR central

5)      I start OSVR server using the attached config file. Here is the  output oft he server:

Oct 20 17:31:16.858 info [OSVR]: 00007FFB741522F8D:\Programm_Files\OSVR\Runtime\bin\osvr_server.exe

Oct 20 17:31:16.859 info [OSVR Server]: Using default config file - pass a filename on the command line to use a different one.

Oct 20 17:31:16.859 info [OSVR Server]: Using config file 'osvr_server_config.json'.

Oct 20 17:31:16.860 info [OSVR Server]: Constructing server as configured...

Oct 20 17:31:16.865 info [OSVR Server]: Loading auto-loadable plugins...

Oct 20 17:31:17.344 info [OSVR Server]: Loading plugins...

Oct 20 17:31:17.345 info [OSVR Server]: Instantiating configured drivers...

Oct 20 17:31:17.345 info [OSVR Server]: External devices found and parsed from config file.

Oct 20 17:31:17.345 info [OSVR Server]: Aliases found and parsed from config file.

Oct 20 17:31:17.345 info [OSVR Server]: Using OSVR HDK for display configuration. Did not find an alternate valid 'display' object in config file.

Oct 20 17:31:17.345 info [OSVR Server]: Triggering automatic hardware detection...

Oct 20 17:31:17.345 info [OSVR Server]: Registering shutdown handler...

Oct 20 17:31:17.345 info [OSVR Server]: Starting server mainloop: OSVR Server is ready to go!

Oct 20 17:31:17.346 info [OSVR Server]: Performing hardware auto-detection.

Oct 20 17:31:17.359 info [OSVR Server]: Sent path tree to clients.

vrpn: Connection request received from 127.0.0.1: 127.0.0.1 59294

Oct 20 17:31:26.813 info [OSVR Server]: Performing hardware auto-detection.

Oct 20 17:31:26.826 info [OSVR Server]: Sent path tree to clients.

vrpn_Endpoint::getOneTCPMessage:  Can't read header (this is normal when a connection is dropped)

vrpn: TCP handling failed, dropping connection (this is normal when a connection is dropped)

6)      I start Tracker Viewer from OSVR central and after a while I get the following messages. So it seems I am still doing something wrong.

Here is the output oft he Tracker Viewer:

Oct 20 17:43:18.777 info [OSVR]: 00007FFB741522F8D:\Programm_Files\OSVR\Runtime\bin\OSVRTrackerView.exe

Oct 20 17:43:18.778 info [OSVR: org.osvr.trackerview]: OSVR client context initialized for org.osvr.trackerview

Oct 20 17:43:18.787 info [OSVR: org.osvr.trackerview]: 00007FFB701D4318

Oct 20 17:43:18.803 info [OSVR: org.osvr.trackerview]: Connected 0 of 0 unconnected paths successfully

Oct 20 17:43:18.804 info [OSVR: org.osvr.trackerview]: Connection process took 16ms: have connection to server, have path tree

[TrackerViewer] No arguments passed: default is as if you passed the following:

--pose /me/hands/left --pose /me/hands/right --pose /me/head

You can specify --pose or --orientation then a path, as many times as you want.

Pass the argument --help for more info.

Oct 20 17:43:18.823 info [OSVR]: Z:\j\workspace\OSVR-Core-Build-Win\BIT\64\TRACING\OFF\VS\12\host\windows\src\osvr\Common\ClientInterface.cpp:38: Interface initialized for /me/hands/left

Oct 20 17:43:18.823 info [OSVR: org.osvr.trackerview]: Could not resolve source for /me/hands/left

Oct 20 17:43:18.823 info [OSVR]: Z:\j\workspace\OSVR-Core-Build-Win\BIT\64\TRACING\OFF\VS\12\host\windows\src\osvr\Common\ClientInterface.cpp:38: Interface initialized for /me/hands/right

Oct 20 17:43:19.826 info [OSVR]: Z:\j\workspace\OSVR-Core-Build-Win\BIT\64\TRACING\OFF\VS\12\host\windows\src\osvr\Client\TrackerRemoteFactory.cpp:93: Constructed a TrackerHandler for DTrack@localhost:5010 sensor 0

Oct 20 17:43:19.826 info [OSVR: org.osvr.trackerview]: Successfully produced handler for /me/hands/right

Oct 20 17:43:19.826 info [OSVR]: Z:\j\workspace\OSVR-Core-Build-Win\BIT\64\TRACING\OFF\VS\12\host\windows\src\osvr\Common\ClientInterface.cpp:38: Interface initialized for /me/head

Oct 20 17:43:19.826 info [OSVR: org.osvr.trackerview]: Could not resolve source for /me/head

VRPN Warning

(3) from DTrack: No response from server for >= 3 seconds

VRPN Warning

(4) from DTrack: No response from server for >= 3 seconds

VRPN Warning

(5) from DTrack: No response from server for >= 3 seconds

VRPN Warning

(6) from DTrack: No response from server for >= 3 seconds

Best regards

RalfRab
[vrpn.cfg.txt](https://github.com/OSVR/OSVR-Docs/files/542142/vrpn.cfg.txt)
[osvr_server_config.json.txt](https://github.com/OSVR/OSVR-Docs/files/542144/osvr_server_config.json.txt)

**Comment by RalfRab** [comment]
issue is solved. Forgot to specify sending port of VRPN server.

**Comment by sroettgermann** [comment]
@RalfRab Can you describe what you've exactly changed? For me it is not working. I think I'm making a little fault... but I don't know which exactly. 😄 

My configuration is looking nearly the same like yours, but I'm always getting the same error you described. If I'm using the VRPN example application, the tracker gets displayed as sensor 0 and provides valid data, but I'm not able to use it in the OSVR TrackerViewer.

Maybe @rpavlik could also help me. 

Thanks in advance!

**Comment by RalfRab** [comment]
Hello,

in the end I had to start a vrpn server in between. So in my case ART was sending to VRPN and VRPN was sending to OSVR. I also had to define the VRPN server to send to a different port, like ART sends to 5000 and VRPN sends to 5001.

Hope it helps.

**Comment by sroettgermann** [comment]
Okay, let me summarize it:

1. on the DTrack/ART Controller you defined the output sending on port 5000
2. on the PC you were running the VRPN server sending data on port 5001
3. in the OSVR config you defined port 5001 as the "reader port" to get the data

Did I got you right?

**Comment by sroettgermann** [comment]
@RalfRab I tested it like I described it, but with no result. Would you be so kind and describe step by step what you have done?! That would be really nice. Maybe you could post your config files too.

**Comment by sroettgermann** [comment]
Okay, it is working. Here is my solution in detail:

- set output in DTrack Controller to IP-address and port (5000) of PC
- on PC start a VRPN server on port 3884 (vrpn_server 3884), don't forget to describe in the config file where the data is coming from (port 5000)
- in the OSVR config file set port 3884 as the server port

For me, this configuration is working fine. 👍
